runtime: nodejs16
service: tools
env: standard
instance_class: F1
handlers:
    - url: .*
      script: auto
automatic_scaling:
    min_idle_instances: 1
    max_idle_instances: 1
    max_instances: 1
    min_pending_latency: automatic
    max_pending_latency: automatic
network: {}
